services:
  # バックエンドAPI
  - type: web
    name: clustering-map-api
    env: python
    region: oregon
    plan: free
    pythonVersion: "3.11"
    buildCommand: |
      pip install -r requirements-final.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: /app
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health
