services:
  # バックエンドAPI
  - type: web
    name: clustering-map-api
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: docker build -t clustering-map-api .
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: /app
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: LOG_LEVEL
        value: "INFO"
      - key: MAX_UPLOAD_SIZE
        value: "50MB"
      - key: CORS_ORIGINS
        value: "https://clustering-map-frontend.onrender.com"
    healthCheckPath: /health
